<?php

namespace Database\Seeders;

use App\Enums\WineRegion;
use App\Enums\WineType;
use App\Models\Wine;
use Illuminate\Database\Seeder;

class WineSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $wines = [
      [
        'name' => 'La Charnivole',
        'appellation' => 'AOP Menetou Salon',
        'country' => 'France',
        'domain' => 'Domaine du Grand Brussy',
        'region' => WineRegion::VAL_DE_LOIRE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Sauvignon Blanc',
        'vintage' => 2023,
        'price' => 14.50,
        'seller' => 'Vinatis',
        'purchase_date' => '2026-03-10',
        'rating' => 17,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => "Bouche tendre, souple, d'une grande fraîcheur. S'accorde avec la volaille, le poisson, les crustacés. Nez frinad aux accents de fruits exotiques, de pêche, de fleurs des champs. Très bon à l'apéro.",
        'nose' => 'Friand, aux accents de fruits exotiques, de pêche, de fleurs des champs.',
        'palate' => 'Tendre, souple, d\'une grande fraîcheur.',
        'pairings' => ['Poisson', 'Viande rouge', 'Fromages affinés', 'Desserts'],
      ],
      [
        'name' => 'Viré Clessé',
        'appellation' => 'AOP Viré-clessé',
        'country' => 'France',
        'domain' => 'Domaine Chailloux',
        'region' => WineRegion::BOURGOGNE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Chardonnay',
        'vintage' => 2023,
        'price' => 16,
        'seller' => 'Vinatis',
        'purchase_date' => '2026-03-10',
        'rating' => 15,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => "Le Viré-Clessé 2023 du Domaine Chailloux est un vin blanc sec issu exclusivement du cépage Chardonnay, cépage emblématique de la Bourgogne. La jeunesse de ce millésime 2023 lui confère une fraîcheur éclatante et un fruité charmant, où s’expriment des arômes de fleurs blanches, d’agrumes et parfois une discrète note de miel ou de fruits à chair blanche.",
        'nose' => 'Arômes de fleurs blanches, d’agrumes et parfois une discrète note de miel ou de fruits à chair blanche.',
        'palate' => 'Fraîcheur, minéralité.',
        'pairings' => ['Fruits de mer', 'Poissons grillés', 'Volaille', 'Fromage de chèvre'],
      ],
      [
        'name' => 'Château Margaux',
        'appellation' => 'Margaux',
        'country' => 'France',
        'domain' => 'Château Margaux',
        'region' => WineRegion::BORDEAUX,
        'wine_type' => WineType::ROUGE,
        'grape' => 'Cabernet Sauvignon, Merlot',
        'vintage' => 2018,
        'price' => 695.00,
        'seller' => 'Nicolas',
        'purchase_date' => '2025-10-12',
        'rating' => 20,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Premier Grand Cru Classé au potentiel exceptionnel.',
        'nose' => 'Cassis, violette, cèdre.',
        'palate' => 'Puissant, soyeux et très long.',
        'pairings' => ['Bœuf', 'Gibier', 'Fromages affinés'],
      ],
      [
        'name' => 'Château Lynch-Bages',
        'appellation' => 'Pauillac',
        'country' => 'France',
        'domain' => 'Château Lynch-Bages',
        'region' => WineRegion::BORDEAUX,
        'wine_type' => WineType::ROUGE,
        'grape' => 'Cabernet Sauvignon, Merlot',
        'vintage' => 2019,
        'price' => 165,
        'seller' => 'Cavavin',
        'purchase_date' => '2025-03-02',
        'rating' => 19,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Grand Pauillac structuré.',
        'nose' => 'Fruits noirs et épices.',
        'palate' => 'Dense et élégant.',
        'pairings' => ['Entrecôte', 'Canard'],
      ],
      [
        'name' => 'Clos de Vougeot',
        'appellation' => 'Clos de Vougeot',
        'country' => 'France',
        'domain' => 'Louis Jadot',
        'region' => WineRegion::BOURGOGNE,
        'wine_type' => WineType::ROUGE,
        'grape' => 'Pinot Noir',
        'vintage' => 2017,
        'price' => 175,
        'seller' => 'Leclerc',
        'purchase_date' => '2024-11-04',
        'rating' => 19,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Grand Cru de Bourgogne.',
        'nose' => 'Cerise noire, sous-bois.',
        'palate' => 'Fin et complexe.',
        'pairings' => ['Bœuf', 'Chevreuil'],
      ],
      [
        'name' => 'Gevrey-Chambertin Vieilles Vignes',
        'appellation' => 'Gevrey-Chambertin',
        'country' => 'France',
        'domain' => 'Harmand-Geoffroy',
        'region' => WineRegion::BOURGOGNE,
        'wine_type' => WineType::ROUGE,
        'grape' => 'Pinot Noir',
        'vintage' => 2020,
        'price' => 69,
        'seller' => 'Intermarché',
        'purchase_date' => '2025-06-10',
        'rating' => 18,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Pinot Noir élégant.',
        'nose' => 'Fruits rouges et épices.',
        'palate' => 'Velouté.',
        'pairings' => ['Magret', 'Volaille'],
      ],
      [
        'name' => 'Meursault',
        'appellation' => 'Meursault',
        'country' => 'France',
        'domain' => 'Louis Latour',
        'region' => WineRegion::BOURGOGNE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Chardonnay',
        'vintage' => 2022,
        'price' => 59,
        'seller' => 'Nicolas',
        'purchase_date' => '2025-02-12',
        'rating' => 18,
        'favorite' => false,
        'buy_again' => true,
        'available' => true,
        'description' => 'Grand Chardonnay.',
        'nose' => 'Beurre et noisette.',
        'palate' => 'Rond et minéral.',
        'pairings' => ['Saint-Jacques', 'Homard'],
      ],
      [
        'name' => 'Chablis Premier Cru',
        'appellation' => 'Chablis',
        'country' => 'France',
        'domain' => 'William Fèvre',
        'region' => WineRegion::BOURGOGNE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Chardonnay',
        'vintage' => 2023,
        'price' => 38,
        'seller' => 'Auchan',
        'purchase_date' => '2025-08-21',
        'rating' => 17,
        'favorite' => false,
        'buy_again' => true,
        'available' => true,
        'description' => 'Blanc frais et minéral.',
        'nose' => 'Agrumes.',
        'palate' => 'Très belle tension.',
        'pairings' => ['Huîtres', 'Poissons'],
      ],
      [
        'name' => 'Côte-Rôtie',
        'appellation' => 'Côte-Rôtie',
        'country' => 'France',
        'domain' => 'E. Guigal',
        'region' => WineRegion::VALLEE_DU_RHONE,
        'wine_type' => WineType::ROUGE,
        'grape' => 'Syrah',
        'vintage' => 2019,
        'price' => 89,
        'seller' => 'Cavavin',
        'purchase_date' => '2024-12-18',
        'rating' => 19,
        'favorite' => true,
        'buy_again' => false,
        'available' => false,
        'description' => 'Grande Syrah.',
        'nose' => 'Poivre et violette.',
        'palate' => 'Long et racé.',
        'pairings' => ['Agneau', 'Gibier'],
      ],
      [
        'name' => 'Châteauneuf-du-Pape',
        'appellation' => 'Châteauneuf-du-Pape',
        'country' => 'France',
        'domain' => 'Domaine de la Janasse',
        'region' => WineRegion::VALLEE_DU_RHONE,
        'wine_type' => WineType::ROUGE,
        'grape' => 'Grenache, Syrah, Mourvèdre',
        'vintage' => 2021,
        'price' => 45,
        'seller' => 'Leclerc',
        'purchase_date' => '2025-04-07',
        'rating' => 18,
        'favorite' => true,
        'buy_again' => false,
        'available' => false,
        'description' => 'Grenache gourmand.',
        'nose' => 'Fruits noirs.',
        'palate' => 'Riche.',
        'pairings' => ['Daube', 'Fromages'],
      ],
      [
        'name' => 'Sancerre Blanc',
        'appellation' => 'Sancerre',
        'country' => 'France',
        'domain' => 'Henri Bourgeois',
        'region' => WineRegion::VAL_DE_LOIRE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Sauvignon Blanc',
        'vintage' => 2024,
        'price' => 23,
        'seller' => 'Carrefour',
        'purchase_date' => '2025-07-18',
        'rating' => 12.5,
        'favorite' => false,
        'buy_again' => true,
        'available' => true,
        'description' => 'Sauvignon vif.',
        'nose' => 'Citron.',
        'palate' => 'Minéral.',
        'pairings' => ['Chèvre', 'Poissons'],
      ],
      [
        'name' => 'Pouilly-Fumé',
        'appellation' => 'Pouilly-Fumé',
        'country' => 'France',
        'domain' => 'Didier Dagueneau',
        'region' => WineRegion::VAL_DE_LOIRE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Sauvignon Blanc',
        'vintage' => 2022,
        'price' => 55,
        'seller' => 'Nicolas',
        'purchase_date' => '2025-03-15',
        'rating' => 19,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Très grand Sauvignon.',
        'nose' => 'Pierre à fusil.',
        'palate' => 'Exceptionnel.',
        'pairings' => ['Homard', 'Bar'],
      ],
      [
        'name' => 'Gewurztraminer',
        'appellation' => 'Alsace',
        'country' => 'France',
        'domain' => 'Hugel',
        'region' => WineRegion::ALSACE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Gewurztraminer',
        'vintage' => 2023,
        'price' => 18,
        'seller' => 'Leclerc',
        'purchase_date' => '2025-05-02',
        'rating' => 17,
        'favorite' => false,
        'buy_again' => true,
        'available' => true,
        'description' => 'Très aromatique.',
        'nose' => 'Litchi.',
        'palate' => 'Ample.',
        'pairings' => ['Foie gras', 'Cuisine asiatique'],
      ],
      [
        'name' => 'Whispering Angel',
        'appellation' => 'Côtes de Provence',
        'country' => 'France',
        'domain' => "Château d'Esclans",
        'region' => WineRegion::PROVENCE,
        'wine_type' => WineType::ROSE,
        'grape' => 'Grenache, Cinsault, Rolle',
        'vintage' => 2024,
        'price' => 24,
        'seller' => 'Carrefour',
        'purchase_date' => '2025-06-21',
        'rating' => 17.5,
        'favorite' => false,
        'buy_again' => true,
        'available' => true,
        'description' => 'Rosé gastronomique.',
        'nose' => 'Pêche.',
        'palate' => 'Très frais.',
        'pairings' => ['Salades', 'Grillades'],
      ],
      [
        'name' => 'Brut Impérial',
        'appellation' => 'Champagne',
        'country' => 'France',
        'domain' => 'Moët & Chandon',
        'region' => WineRegion::CHAMPAGNE,
        'wine_type' => WineType::CHAMPAGNE,
        'grape' => 'Chardonnay, Pinot Noir, Pinot Meunier',
        'vintage' => 2021,
        'price' => 55,
        'seller' => 'Nicolas',
        'purchase_date' => '2024-12-24',
        'rating' => 18,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Champagne emblématique.',
        'nose' => 'Brioche.',
        'palate' => 'Bulles fines.',
        'pairings' => ['Apéritif', 'Fruits de mer'],
      ],
      [
        'name' => 'Mas de Daumas Gassac',
        'appellation' => 'IGP Saint-Guilhem-le-Désert',
        'country' => 'France',
        'domain' => 'Mas de Daumas Gassac',
        'region' => WineRegion::LANGUEDOC,
        'wine_type' => WineType::ROUGE,
        'grape' => 'Cabernet Sauvignon, Merlot',
        'vintage' => 2020,
        'price' => 42,
        'seller' => 'Leclerc',
        'purchase_date' => '2025-02-10',
        'rating' => 18,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Grand vin du Languedoc.',
        'nose' => 'Mûre.',
        'palate' => 'Complexe.',
        'pairings' => ['Agneau', 'Bœuf'],
      ],
      [
        'name' => 'Vin Jaune',
        'appellation' => 'Château-Chalon',
        'country' => 'France',
        'domain' => 'Domaine Macle',
        'region' => WineRegion::JURA,
        'wine_type' => WineType::BLANC,
        'grape' => 'Savagnin',
        'vintage' => 2017,
        'price' => 58,
        'seller' => 'Cavavin',
        'purchase_date' => '2024-10-08',
        'rating' => 19,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => 'Vin jaune traditionnel.',
        'nose' => 'Noix.',
        'palate' => 'Très long.',
        'pairings' => ['Comté', 'Poulet aux morilles'],
      ],
      [
        'name' => 'Clos de la Roche Noire',
        'appellation' => 'Anjou AOP',
        'country' => 'France',
        'domain' => 'Domaine de Montgilet',
        'region' => WineRegion::VAL_DE_LOIRE,
        'wine_type' => WineType::BLANC,
        'grape' => 'Chenin',
        'vintage' => 2024,
        'price' => 14.90,
        'seller' => 'Vinatis',
        'purchase_date' => '2026-07-10',
        'rating' => 18,
        'favorite' => true,
        'buy_again' => true,
        'available' => false,
        'description' => "Le Domaine De Montgilet est une référence de la région. Clos de la Roche Noire est un Chenin issu d'un terroir riche. L'élevage en barrique offre des notes chaudes et torréfiées au nez, suivies par une bouche généreuse et fraîche. Dominé par des arômes de fruits blancs, cet Anjou blanc offre un ensemble soyeux et équilibré, très abouti. Dégusté au Moulin de l'Abbaye (Brantôme) le 10 juillet 2026.",
        'nose' => 'Des arômes de fleurs blanches, fruits jaunes et agrumes.',
        'palate' => 'Blanc Sec souple et fruité.',
        'pairings' => ['Poisson', 'ruits de mer', 'Dessert'],
      ],

    ];

    foreach ($wines as $wine) {
      Wine::create($wine);
    }

  }
}
